---
name: Landing Zone Vending Deployment

on:
  push:
    branches:
      - main
    paths:
      - src/configuration/sub-sap-prd-01.parameters.bicepparam
      - src/orchestration/main.bicep

  workflow_dispatch: {}

env:
  managementGroupId: ${{ vars.MANAGEMENT_GROUP_ID }}
  location: ${{ vars.LOCATION }}
  moduleName: LandingZoneVendingMachine
  templateFile: src/orchestration/main.bicep
  templateParameterFile: src/configuration/sub-sap-prd-01.parameters.bicepparam
  runNumber: ${{ github.run_number }}
  secret: ${{ secrets.AZURE_CREDENTIALS }}
  existingSubscriptionId: ${{ secrets.existingSubscriptionId }}

jobs:
  Build:
    runs-on: ubuntu-latest 
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Bicep Build
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: |
            az bicep build -f ${{ env.templateFile }} --stdout

  Validate:
    runs-on: ubuntu-latest
    needs: Build 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run PSRule Analysis
        uses: microsoft/ps-rule@latest
        with:
          inputType: inputPath
          inputPath: ${{ env.templateFile }}
          modules: PSRule.Rules.Azure, PSRule.Rules.CAF
          baseline: Azure.GA_2023_09
          outputFormat: NUnit3
          outputPath: reports/ps-rule-results.xml
        continue-on-error: false

      - name: Azure Login
        uses: azure/login@v1.4.5
        with:
          creds: ${{ env.secret }}

      - name: Validate Deployment
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: |
            az deployment mg validate -n "${{ env.moduleName }}-${{ env.runNumber }}" -m ${{ env.managementGroupId }} -l ${{ env.location }} -f ${{ env.templateFile }} -p ${{ env.templateParameterFile }} -p ${{ env.existingSubscriptionId }}
            
  WhatIf:
    runs-on: ubuntu-latest
    needs: Validate
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Azure Login
        uses: azure/login@v1.4.5
        with:
          creds: ${{ env.secret }}
          
      - name: What-If
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: |
            az deployment mg what-if -n "${{ env.moduleName }}-${{ env.runNumber }}" -m ${{ env.managementGroupId  }} -l ${{ env.location }} > whatif -f ${{ env.templateFile }} -p ${{ env.templateParameterFile }} --exclude-change-types Ignore NoChange Unsupported --result-format FullResourcePayloads

  Deploy:
    runs-on: ubuntu-latest
    needs: WhatIf
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Azure Login
        uses: azure/login@v1.4.5
        with:
          creds: ${{ env.secret }}
        
      - name: Create Deployment
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: | 
            az deployment mg create -n "${{ env.moduleName }}-${{ env.runNumber }}" -m ${{ env.managementGroupId }} -l ${{ env.location }} -f ${{ env.templateFile }} -p ${{ env.templateParameterFile }} -p ${{ env.existingSubscriptionId }}
